.MODEL SMALL
.STACK 100
.DATA

	;MENU DISPLAYS
	Welcome DB "			||WELCOME TO THE POINT OF SALES SYSTEM|| $"
	login DB "				1. LOGIN$"
	register DB "				2. REGISTER$"
	logout DB "				3. LOGOUT$"
	exit DB "				0. EXIT$"
	entering db "				CHOICE : $"
	invalid DB "Invalid input. Please try again: $"
	exitconfirmed DB "ARE YOU SURE YOU WANT TO EXIT? (Y/N) : $"
	exitsuc DB "EXIT SUCCESS.$"
	NL DB 0AH,0DH, '$'
	INP DB ?
		;LOGIN FUNCTIONS
		LOGINSUC DB "LOGIN SUCCESS!$"
		LOGINFAIL DB "LOGIN FAILED, TRY AGAIN!$"
		LOGINTRUE DB 0
		ALREADYLOGGEDIN DB "USER IS ALREADY LOGGED IN! ENTERING FUNCTIONS MENU INSTEAD...$"
			;INPUTTED USERNAME
		USERPROMPT DB "ENTER YOUR USERNAME : $"
		INUSER LABEL BYTE
		MAXUSER DB 11
		ACTUSER DB ?
		OUTUSER DB 11 DUP('$') 
			;INPUTTED PASSWORD
		PASSWPROMPT DB "ENTER YOUR PASSWORD : $"
		INPASS LABEL BYTE
		MAXPASS DB 11
		ACTPASS DB ?
		OUTPASS DB 11 DUP('$') 
		
		

		;REGISTER FUNCTION
			;INPUTTED USERNAME
		REGUSERPROMPT DB "ENTER YOUR USERNAME (MAX 10 CHARACTERS) : $"
		REGINUSER LABEL BYTE
		REGMAXUSER DB 11
		REGACTUSER DB ?
		REGOUTUSER DB 11 DUP('$') 
			;INPUTTED PASSWORD
		REGPASSWPROMPT DB "ENTER YOUR PASSWORD (MAX 10 CHARACTERS): $"
		REGINPASS LABEL BYTE
		REGMAXPASS DB 11
		REGACTPASS DB ?
		REGOUTPASS DB 11 DUP('$') 
		
			;CONFIRMATION 
		REGCOMPLETE DB "REGISTRATION COMPLETE!$"
		
		;LOGOUT FUNCTION
		LOGOUTPROMPT DB "ARE YOU SURE YOU WANT TO LOGOUT? (Y/N): $"
		SUCCESSLOGOUT DB "SUCCESSFULLY LOGGED OUT.$"
		NOTLOGGEDIN DB "USER IS NOT LOGGED IN.$"
		
	;FUNCTIONS MENU 

	;MENU DISPLAYS
	funcexit DB " SUCCESSFULLY EXITED FROM FUNCTIONS MENU.$"
	FUNCMENU DB "			||FUNCTIONS MENU|| $"
	inventory DB "				1. VIEW INVENTORY$" 
	sale      DB "				2. PROCESS NEW SALE$" ;COMPUTE SALES PRICE / RECEIPT 
	report    DB "				3. VIEW SALES REPORT$" ; TOTAL PROFITS
	
	; INVENTORY DATA
    INVTITLE    DB 0AH,0DH, "			|| INVENTORY LIST ||$", 0AH,0DH, '$'
    ITEM1       DB "1. Soda Can    - Price: RM2.00 | Stock: $"
    STOCK1      DW 550  
	PRICE1 		DW 2
    ITEM2       DB "2. Chips       - Price: RM3.00 | Stock: $"
    STOCK2      DW 265
	PRICE2		DW 3
    ITEM3       DB "3. Sandwich    - Price: RM5.00 | Stock: $"
    STOCK3      DW 124
	PRICE3		DW 5
	
	;NEW SALES DATA
	INVREFER 	DB 0AH,0DH, 'WHICH STOCK TO SELL !!DO NOT MESS UP THIS PART!!(CURRENT INVENTORY ABOVE) $',0AH,0DH,'$'
	INVSALE		DB 0AH,0DH,'INVALID STOCK DETECTED,TRY AGAIN!(1-3) $',0AH,0DH,'$'
	SALEPROMPT 	DW ?
	SCONFIRM	DB 0AH,0DH,'ARE YOU CONFIRMED TO MAKE THIS SALE?(Y/N):$'
	SYES		DB 0AH,0DH,'SALES IS CONFIRMED,NOW RETURNING TO FUNCTIONS MENU!$',0AH,0DH,'$'
	SNO 		DB 0AH,0DH,'SALE CANCELED,NOW RETURNING TO FUNCTIONS MENU!$',0AH,0DH,'$'
	SIN			DB 0AH,0DH,'INVALID INPUT DETECTED,TRY AGAIN!$',0AH,0DH,'$'
	;NEW SALES DATA
	NSTOCK1		DW ?
	NSTOCK2		DW ?           
	NSTOCK3		DW ?
	SELL1		DB 0AH,0DH,'HOW MUCH SODA TO BE SOLD: $',0AH,0DH,'$'
	SOLD        DB 4 DUP(?)    
	SELL2		DB 0AH,0DH,'HOW MUCH CHIPS TO BE SOLD: $',0AH,0DH,'$'
	SELL3		DB 0AH,0DH,'HOW MUCH SANDWICH TO BE SOLD: $',0AH,0DH,'$'	
	OVRSTOCK 	DB 0AH,0DH,'SOLD AMOUNT GREATER THAN STOCK,TRY AGAIN$',0AH,0DH,'$'
	;SALES REPORT DATA
	TTLSALE 	DB 0AH,0DH,'==========TOTAL SALES==========$',0AH,0DH,'$'
	REPITEM1	DB 0AH,0DH,'1. Soda Can    - Price: RM2.00 | Sold:RM'
	AMNTITEM1	DB ?
	REPSTOCK1	DW ?

	
	
	
.CODE
MAIN PROC
	MOV AX , @DATA
	MOV DS , AX 
	
;------------------------------------------------------------------------
;------------------------------------------------------------------------
	LOGINMENU:
	; PRELOAD CREDENTIALS (USERNAME = "1", PASSWORD = "1")!!!!!!!!!!!DELETE AFTER DONE WITH THIS!!
	MOV REGACTUSER, 1
	MOV REGOUTUSER[0], '1'
	MOV REGACTPASS, 1
	MOV REGOUTPASS[0], '1'
	
	
	;login menu
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, Welcome
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, login
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, register
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, logout
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, exit
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, entering
	INT 21H
	
	;login menu end
	
	;menu input, output
	RESETCHOICE:
	MOV AH, 01H
	INT 21H ;choice is stored in AL!!
	CMP AL,'1'
	JE LOGINJJ
	CMP AL,'2'
	JE REGISTERJJ
	CMP AL, '3' 
	JE LOGOUTJJ
	CMP AL,'0'
	JNE elsej
	
	;EXIT CONFIRMATION
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, exitconfirmed
	INT 21H
	MOV AH, 01H ;USER RESPONSE
	INT 21H 
	CMP AL, 'Y'
	JE EXITJJ
	CMP AL,'0'
	JE EXITJJ ;!!!!!!!!!!!!!!!!!!!!!!!!TYLER CHAANGED THIS BECAUSE MOVING HIS FAT FINGERS IS TORTURE (and yes i know i prolly wasted more time typing this)!!!!!!!!
	CMP AL, 'y'
	JE EXITJJ
	CMP AL, 'N'
	JE LOGINMENUJJ
	CMP AL, 'n'
	JE LOGINMENUJJ
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, invalid
	INT 21H
	
	LOGINMENUJJ:
	JMP LOGINMENU
	
	LOGINJJ:
	JMP LOGINJ
	
	REGISTERJJ:
	JMP REGISTERJ
	
	LOGOUTJJ:
	JMP LOGOUTJ
	
	ALREADYLOGGEDINJJ:
	JMP ALREADYLOGGEDINJ
	
	LOGIN_FAILJJ:
	JMP LOGIN_FAILJ
	
	EXITJJ:
	JMP EXITJ
	
	elsej:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, invalid
	INT 21H
	JMP RESETCHOICE ;return to main menu
	
	LOGINJ:
	;LOGIN FUNCTION
	CMP LOGINTRUE,1
	JE ALREADYLOGGEDINJJ
	; REJECT LOGIN IF NOT REGISTERED
	CMP REGACTUSER, 0
	JE LOGIN_FAILJJ
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, USERPROMPT
	INT 21H
	MOV AH, 0AH
	LEA DX, INUSER
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, PASSWPROMPT
	INT 21H
	MOV AH, 0AH
	LEA DX, INPASS
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	
	;COMPARE INPUTTED TO REGISTERED
	;--- COMPARE USERNAME LENGTH ---
	MOV AL, ACTUSER
	CMP AL , REGACTUSER
	JNE LOGIN_FAILJ
	
	;--- COMPARE USERNAME CHARACTERS ---
	MOV SI,0 ;RESET SO ARRAY COUNTS FROM 0
	MOV DI,0
	MOV CL, ACTUSER
	MOV CH, 0 ;CX = LOOP AMOUNT
	
	CHECK_USERNAME_LOOP:
		MOV AL, OUTUSER[SI]
		CMP AL, REGOUTUSER[DI]
		JNE LOGIN_FAILJ
		INC SI
		INC DI
		
	LOOP CHECK_USERNAME_LOOP
	
	;--- CHECK PASSWORD LENGTH ---
	MOV AL, ACTPASS
	CMP AL , REGACTPASS
	JNE LOGIN_FAILJ
	
	;COMPARE PASSWORD CHARACTERS ---
	MOV SI,0 ;RESET SO ARRAY COUNTS FROM 0
	MOV DI,0
	MOV CL, ACTPASS
	MOV CH, 0 ;CX = LOOP AMOUNT
	
	
	CHECK_PASSWORD_LOOP:
		MOV AL, OUTPASS[SI]
		CMP AL, REGOUTPASS[DI]
		JNE LOGIN_FAILJ
		INC SI
		INC DI
		
	LOOP CHECK_PASSWORD_LOOP
	
	;LOGIN SUCCESSFULLY
	MOV AH, 09H
	LEA DX, LOGINSUC
	INT 21H
	MOV LOGINTRUE,1 ;SET FLAG FOR LOG IN
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	JMP FUNCTIONMENUJ ;REPLACE THIS TO GO INTO FUNCTIONS
	
	ALREADYLOGGEDINJ:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, ALREADYLOGGEDIN
	INT 21H
	JMP FUNCTIONMENUJ
	
	LOGIN_FAILJ:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, LOGINFAIL
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	JMP LOGINMENU
	
	REGISTERJ:
	;REGISTRATION FUNCTION
	;RECORD
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, REGUSERPROMPT
	INT 21H
	MOV AH, 0AH
	LEA DX, REGINUSER
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, REGPASSWPROMPT
	INT 21H
	MOV AH, 0AH
	LEA DX, REGINPASS
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, REGCOMPLETE
	INT 21H
	;MOV AH, 09H
	;LEA DX, NL
	;INT 21H
	JMP LOGINMENU
	
	LOGOUTJ:
	;LOGOUT FUNCTION
	;CHECK FOR IF LOGGED IN
	CMP LOGINTRUE , 1
	JE LOGGEDINJ
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, NOTLOGGEDIN
	INT 21H
	JMP LOGINMENU
	
	LOGGEDINJ:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, LOGOUTPROMPT
	INT 21H
	
	MOV AH, 01H ;USER RESPONSE
	INT 21H 
	
	CMP AL, 'Y'
	JE LOGGINGOUTJ
	CMP AL, 'y'
	JE LOGGINGOUTJ
	CMP AL, 'N'
	JE NOTLOGGINGOUTJ
	CMP AL, 'n'
	JE NOTLOGGINGOUTJ
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, invalid
	INT 21H
	JMP LOGGEDINJ

	NOTLOGGINGOUTJ:
	JMP LOGINMENU

	LOGGINGOUTJ:
	;LOGGEDOUT RESET FLAG
	MOV LOGINTRUE, 0
	
	; CLEAR INPUT
	MOV ACTUSER, 0
	MOV ACTPASS, 0
	
	; CLEAR BUFFER, ADD $
	MOV CX, 11
	MOV SI, 0
	CLEAR_BUFFERS:
		MOV OUTUSER[SI], '$'
		MOV OUTPASS[SI], '$'
		INC SI
	LOOP CLEAR_BUFFERS
	
	; LOGOUT CONFIRMATION
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, SUCCESSLOGOUT
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	JMP LOGINMENU
;------------------------------------------------------------------------
;------------------------------------------------------------------------

	
	;function menu
	FUNCTIONMENUJ:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, FUNCMENU
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, inventory
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, sale
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, report
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, exit
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, entering
	INT 21H
	
	RESETCHOICEfunc:
	MOV AH, 01H
	INT 21H ;choice is stored in AL!!
	CMP AL,'1'
	JE inventoryjj
	CMP AL,'2'
	JE NEWSALESJJ
	CMP AL, '3'
	JE reportjj
	CMP AL,'0'
	JNE elsefuncj
	
	;EXIT CONFIRMATION
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, exitconfirmed
	INT 21H
	MOV AH, 01H ;USER RESPONSE
	INT 21H 
	CMP AL, 'Y'
	JE LOGINMENUJJ2
	CMP AL, 'y'
	JE LOGINMENUJJ2
	CMP AL, 'N'
	JE FUNCTIONMENUJJ
	CMP AL, 'n'
	JE FUNCTIONMENUJJ
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, invalid
	INT 21H
	
	LOGINMENUJJ2:
	JMP LOGINMENU
	
	FUNCTIONMENUJJ:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, funcexit
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	JMP FUNCTIONMENUJ
	
	elsefuncj:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, invalid
	INT 21H
	JMP RESETCHOICEfunc ;return to menu
	
	inventoryjj:
	CALL inventoryj
	JMP FUNCTIONMENUJ ;tyler moved the jmp functionmenuj to here because the code didnt work the way he have intended :( 
	salejj:
	JMP RESETCHOICEfunc
	;JMP salej
	
	reportjj:
	JMP RESETCHOICEfunc
	;JMP reportj
	
	NEWSALESJJ:
	JMP NEWSALES
	inventoryj:
	;inventory menu display
	
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, INVTITLE
	INT 21H
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, ITEM1
	INT 21H
	MOV AX, STOCK1
	CALL PRINT_NUM_4DIGIT
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, ITEM2
	INT 21H
	MOV AX, STOCK2
	CALL PRINT_NUM_4DIGIT
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, ITEM3
	INT 21H
	MOV AX, STOCK3
	CALL PRINT_NUM_4DIGIT
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	RET
	;!!!!!!!!!!!!!!!!!moved the jmp FUNCTIONMENUJ to line 522 and changed to RET because the code below this (NEWSALES)wont work without being called


	NEWSALES:
	;PROCCESSING NEW SALES 
	MOV AH,09H
	LEA DX,NL
	INT 21H
	CALL inventoryj
	MOV AH,09H
	LEA DX,INVREFER
	INT 21H	
	MOV AH,09H
	LEA DX,NL
	INT 21H
	MOV AH,01H	
	INT 21H ;choice is stored in AL!!
	CMP AL, 0DH
	JE INVS
	CMP AL,'1'
	JE SSODAS
	CMP AL,'2'
	JE SCHIPS
	CMP AL, '3'
	JE SSANDS
	CMP AL,'4'
	JE SHOW
	CMP AL,'0'
	JLE INVS
	CMP AL,'5' ;CHANGE BACK TO 4
	JGE INVS
	JMP NEWSALES
	
	
	INVS:
	JMP INV
	RET
	INV:
	LEA DX,INVSALE
	INT 21H
	RET
	
	SSODAS:
	CALL SSODA
	JMP FUNCTIONMENUJ
	
	SHOW:
	MOV AX,NSTOCK1
	CALL PRINT_NUM_4DIGIT
	;MOV AX,STOCK1
	;CMP AX,SOLD1
	JMP FUNCTIONMENUJ
	
SSODA :
	MOV AH, 09H
    LEA DX, NL
    INT 21H

    MOV AH, 09H
    LEA DX, SELL1
    INT 21H

    CALL INP4DIGITS          
	CALL CONV
	MOV BX,STOCK1
	;CALL CONV 
	CMP AX,BX
	CMP STOCK1,AX
	JLE INVSTOCKS ;write jump not enough stock
	;write if sufficient stock
    MOV AH, 09H
    LEA DX, NL
    INT 21H
    JMP SCONFIRMM
	INT 21H 
	RET

	
	MOV AH, 09H
    LEA DX, NL 
    INT 21H
	JMP SCONFIRMM
	;SALES CONFIRMATION
		
	SCHIPS:
	CALL SCHIP
	JMP FUNCTIONMENUJ
	SSANDS:
	CALL SSAND
	JMP FUNCTIONMENUJ
	SCHIP:
	;SELLING AMOUNT CHECK FOR CHIPS 
	MOV AH,09H
	LEA DX, NL
	INT 21H
	LEA DX,SELL2
	INT 21H
	CALL INP4DIGITS 
	;MOV SOLD,AX
	MOV AH, 09H
    LEA DX, NL
    INT 21H
	JMP SCONFIRMM
	;SALES CONFIRMATION

	SSAND:
	CALL SSANDWICH
	JMP FUNCTIONMENUJ
	
	SSANDWICH:
	;SELLING AMOUNT CHECK FOR SANDWICH 
	MOV AH,09H
	LEA DX, NL
	INT 21H
	LEA DX,SELL3
	INT 21H
	CALL INP4DIGITS 
	;MOV SOLD,AX
	MOV AH, 09H
    LEA DX, NL
    INT 21H
	JMP SCONFIRMM
	
	INVSTOCKS:
	JMP INVSTOCK
	RET
	
	;SALE CONFIRMATION
	SCONFIRMM:
	LEA DX,SCONFIRM 
	INT 21H
	MOV AH,01H
	INT 21H
	CMP AL,'Y'
	JE SYESS
	CMP AL, 'y'
	JE	SYESS
	CMP AL,'N'
	JE SNOO
	CMP AL,'n'
	JE SNOO
	CMP AL,'O'
	JNE SINN
	RET 
	
	SYESS:
	MOV AH,09H	
	LEA DX,SYES
	INT 21H
	SUB STOCK1,AX
	SUB STOCK1,'0'
	MOV NSTOCK1,AX
	INT 21H	
	CALL CONV
	RET
	
	SNOO:
	MOV AH,09H
	LEA DX,SNO
	INT 21H
	RET
	
	SINN:
	MOV AH,09H
	LEA DX,SIN
	INT 21H
	JMP SCONFIRMM
	
	INVSTOCK:
	MOV AH,09H
	LEA DX,OVRSTOCK
	INT 21H 
	RET
	
	;========SALES REPORT=======


	

	EXITJ:
	MOV AH, 09H
	LEA DX, NL
	INT 21H
	MOV AH, 09H
	LEA DX, exitsuc
	INT 21H
	MOV AX,4C00H
	INT 21H

MAIN ENDP


;to use PRINT_NUM_4DIGIT, just write it like :
;mov ax , (variable/digit)
;call PRINT_NUM_4DIGIT
PRINT_NUM_4DIGIT PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    MOV BX, AX          ; Save original number in BX

    ; 1. THOUSANDS (Divide by 1000)
    MOV AX, BX
    MOV DX, 0
    MOV CX, 1000
    DIV CX              ; AX = Quotient, DX = Remainder
    MOV BX, DX          ; Save remainder (0-999)
    
    MOV DL, AL
    ADD DL, '0'
    MOV AH, 02H
    INT 21H             ; Print Thousands

    ; 2. HUNDREDS (Divide by 100)
    MOV AX, BX
    MOV DX, 0
    MOV CX, 100
    DIV CX              ; AX = Quotient, DX = Remainder
    MOV BX, DX          ; Save remainder (0-99)
    
    MOV DL, AL
    ADD DL, '0'
    MOV AH, 02H
    INT 21H             ; Print Hundreds

    ; 3. TENS (Divide by 10)
    MOV AX, BX
    MOV DX, 0
    MOV CX, 10
    DIV CX              ; AX = Quotient (Tens), DX = Remainder (Ones)
    MOV BX, DX          ; Save remainder (Ones) in BX
    
    MOV DL, AL
    ADD DL, '0'
    MOV AH, 02H
    INT 21H             ; Print Tens

    ; 4. ONES
    MOV DL, BL
    ADD DL, '0'
    MOV AH, 02H
    INT 21H             ; Print Ones

    POP DX
    POP CX
    POP BX
    POP AX
    RET
PRINT_NUM_4DIGIT ENDP

INP4DIGITS PROC
    MOV CX, 4                       
    LEA SI, Sold                  

INP_LOOP:
    MOV AH, 01H                     
    INT 21H
    
    CMP AL, 0DH                     ; Did user press Enter?
    JE  FILL_ZEROES                 ; If yes, pad the rest of the array
    
    MOV [SI], AL                    ; Store valid character
    INC SI                          
    LOOP INP_LOOP
    RET

FILL_ZEROES:
    ; Optional: Pad remaining array slots with '0' if user pressed Enter early
    JCXZ DONE                       ; If CX is already 0, finish
PAD_LOOP:
    MOV BYTE PTR [SI], '0'
    INC SI
    LOOP PAD_LOOP
DONE:
    RET
INP4DIGITS ENDP
CONV PROC
    XOR AX, AX                      ; AX = 0
    MOV CX, 4                       ; 4 digits
    LEA SI, SOLD                   ; Point to 'digits' array
    MOV BX, 10                      ; Base 10 multiplier

CONV_LOOP:
    MUL BX                          ; AX = AX * 10
    MOV DL, [SI]                    ; Read ASCII byte
    SUB DL, '0'                     ; Strip ASCII offset
    XOR DH, DH                      ; Clear DH
    ADD AX, DX                      ; AX = (AX * 10) + Digit
    INC SI                          ; Next character
    LOOP CONV_LOOP

    RET                             ; Converted value is returned in AX
CONV ENDP

END MAIN
